# coding: utf-8
"""LLVM backend tests.

覆盖：

- LIR -> LLVM IR 结构（module 契约：qy_fn_table / qy_main / main）；
- C ABI 正确性（``%qy_value`` 以 sret/byval 传递）；
- 端到端：LLVM IR -> ``llc`` -> 与 libqy 链接 -> 运行，结果与 register VM 一致。

端到端用例在缺少 ``llc`` / ``clang`` 时自动跳过。
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from qy.backend.llvm.emit import emit
from qy.build.artifact import LIR
from qy.build.pipeline import compile_source_to_kind
from qy.build.pipeline import lir_artifact
from qy.passes.pass_base import PipelineSession
from qy.session.runtime_space import create_standard_runtime_space

ROOT = Path(__file__).resolve().parents[1]
INCLUDE_DIR = ROOT / "qy" / "resources" / "libqy" / "include"
RUNTIME_C = ROOT / "qy" / "resources" / "libqy" / "src" / "runtime.c"

_LLC = shutil.which("llc")
_CLANG = shutil.which("clang")

requires_toolchain = pytest.mark.skipif(
    _LLC is None or _CLANG is None,
    reason="needs llc and clang",
)


def _compile_lir(source: str):
    result = compile_source_to_kind(
        source, PipelineSession(env=create_standard_runtime_space()), kind=LIR
    )
    return lir_artifact(result)


def test_llvm_emit_module_contract():
    ll = emit(_compile_lir("(+ 1 2)"))

    assert ll.startswith("; generated by qy llvm backend")
    assert "@qy_fn_table = global" in ll
    assert "@qy_fn_table_size = constant i64" in ll
    assert "define void @qy_main(" in ll
    assert "define i32 @main(" in ll
    # C ABI: 32-byte struct passed via sret / byval, and opaque pointers.
    assert "ptr sret(%qy_value) align 8" in ll
    assert "ptr byval(%qy_value) align 8" in ll
    assert "%qy_value*" not in ll


def test_llvm_emit_rejects_non_compat_dialect():
    from qy.ir.lir import LIRProgram

    with pytest.raises(ValueError):
        emit(LIRProgram((), dialect="abstract-machine"))


def _run_native(source: str, tmp_path: Path) -> str:
    llc = _LLC
    clang = _CLANG
    assert llc is not None and clang is not None
    runtime_obj = tmp_path / "runtime.o"
    subprocess.run(
        [clang, "-O0", "-I", str(INCLUDE_DIR), "-c", str(RUNTIME_C), "-o", str(runtime_obj)],
        check=True,
        capture_output=True,
        text=True,
    )
    ll_path = tmp_path / "program.ll"
    obj_path = tmp_path / "program.o"
    bin_path = tmp_path / "program.bin"
    ll_path.write_text(emit(_compile_lir(source)), encoding="utf-8")
    subprocess.run(
        [llc, "-filetype=obj", str(ll_path), "-o", str(obj_path)],
        check=True,
        capture_output=True,
        text=True,
    )
    subprocess.run(
        [clang, str(obj_path), str(runtime_obj), "-o", str(bin_path)],
        check=True,
        capture_output=True,
        text=True,
    )
    completed = subprocess.run([str(bin_path)], check=True, capture_output=True, text=True)
    return completed.stdout


@requires_toolchain
@pytest.mark.parametrize(
    ("source", "expected"),
    [
        ("(+ 1 2)", "3\n"),
        ("(+ (* 6 7) 0)", "42\n"),
        ("(let ((+ (lambda (left right) left))) (+ 42 0))", "42\n"),
        (
            """
            (let ()
              (defun sum-to (n acc)
                (cond
                  ((= n 0) acc)
                  (true (sum-to (- n 1) (+ acc n)))))
              (sum-to 300 0))
            """,
            "45150\n",
        ),
    ],
)
def test_llvm_native_matches_register_vm(tmp_path, source, expected):
    assert _run_native(source, tmp_path) == expected


@requires_toolchain
def test_llvm_cli_emits_ir(tmp_path):
    from click.testing import CliRunner

    from qy.cli._app import build_cli

    source_path = tmp_path / "program.qy"
    source_path.write_text("(+ 1 2)", encoding="utf-8")
    result = CliRunner().invoke(build_cli(), ["llvm", str(source_path)])

    assert result.exit_code == 0, result.output
    assert result.output.startswith("; generated by qy llvm backend")
