# coding: utf-8
"""IR models — HIR, MIR, and LIR.

Public API (re-exported from qy/__init__.py):
    from qy.ir import ProgramIR, Binding, CallExpr, ...
    from qy.ir import LIRProgram, LIRFunction, LIRInstruction, ...
    from qy.ir import MIRProgram, MIRFunction, MIRInstruction, MIRTerminator, ...
"""

from __future__ import annotations

from qy.ir.hir import (
    AllExpr,
    ApplyExpr,
    AssertExpr,
    Binding,
    BindingSource,
    CacheExpr,
    CallExpr,
    CondClause,
    CondExpr,
    DefeffectExpr,
    DefineExpr,
    DefunExpr,
    dump_ir,
    EffectHandler,
    FromImportExpr,
    HandleExpr,
    IRExpr,
    LambdaExpr,
    LetBinding,
    LetExpr,
    LiteralExpr,
    MacroExpr,
    ModuleExpr,
    ParallelExpr,
    PerformExpr,
    PipelineExpr,
    ProgramIR,
    QuoteExpr,
    RaceExpr,
    ResumeExpr,
    RuntimeEvalExpr,
    SymbolRefExpr,
    UnresolvedSymbolExpr,
)

from qy.ir.lir import (
    dump_lir,
    LIRBindingAddr,
    LIRBindingSlot,
    LIRBindingState,
    LIRContinuationLayout,
    LIRDialect,
    LIRFrameKind,
    LIRFrameLayout,
    LIRFunction,
    LIRHandlerLayout,
    LIRInstruction,
    LIRInstructionIndex,
    LIROpcode,
    LIRProgram,
    LIRRegister,
    LIRSlotIndex,
    LIRSymbolMeta,
    LIRSymbolSpaceId,
    LIRSymbolSpaceLayout,
    verify_lir,
)

from qy.ir.mir import (
    dump_mir,
    MIRBlock,
    MIRBlockId,
    MIRConstantPool,
    MIRFunction,
    MIRInstruction,
    MIROpcode,
    MIRProgram,
    MIRRegister,
    MIRTerminator,
    MIRTerminatorOpcode,
    verify_mir,
)

__all__ = [
    # HIR
    "AllExpr",
    "ApplyExpr",
    "AssertExpr",
    "Binding",
    "BindingSource",
    "CacheExpr",
    "CallExpr",
    "CondClause",
    "CondExpr",
    "DefeffectExpr",
    "DefineExpr",
    "DefunExpr",
    "dump_ir",
    "EffectHandler",
    "FromImportExpr",
    "HandleExpr",
    "IRExpr",
    "LambdaExpr",
    "LetBinding",
    "LetExpr",
    "LiteralExpr",
    "MacroExpr",
    "ModuleExpr",
    "ParallelExpr",
    "PerformExpr",
    "PipelineExpr",
    "ProgramIR",
    "QuoteExpr",
    "RaceExpr",
    "ResumeExpr",
    "RuntimeEvalExpr",
    "SymbolRefExpr",
    "UnresolvedSymbolExpr",
    # LIR
    "dump_lir",
    "LIRBindingAddr",
    "LIRBindingSlot",
    "LIRBindingState",
    "LIRContinuationLayout",
    "LIRDialect",
    "LIRFrameKind",
    "LIRFrameLayout",
    "LIRFunction",
    "LIRHandlerLayout",
    "LIRInstruction",
    "LIRInstructionIndex",
    "LIROpcode",
    "LIRProgram",
    "LIRRegister",
    "LIRSlotIndex",
    "LIRSymbolMeta",
    "LIRSymbolSpaceId",
    "LIRSymbolSpaceLayout",
    "verify_lir",
    # MIR
    "dump_mir",
    "MIRBlock",
    "MIRBlockId",
    "MIRConstantPool",
    "MIRFunction",
    "MIRInstruction",
    "MIROpcode",
    "MIRProgram",
    "MIRRegister",
    "MIRTerminator",
    "MIRTerminatorOpcode",
    "verify_mir",
]