services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        - APT_CACHE_PROXY=http://host.docker.internal:3142
        - BUN_REGISTRY=http://host.docker.internal:4873
    volumes:
      - ..:/workspaces/Qy:cached
      - dev-venv:/workspaces/Qy/.venv
      - dev-node-modules:/workspaces/Qy/node_modules
      - zsh-history:/home/ge/.zsh_history
      - ${HOME}/.claude:/home/ge/.claude:cached
      - ${HOME}/.claude.json:/home/ge/.claude.json:cached
    command: sleep infinity
volumes:
  dev-venv:
  dev-node-modules:
  zsh-history:
  zshrc: