# coding: utf-8
"""Emit LLVM IR from LIR (compat dialect).

设计：

- ``%qy_value`` 布局与 ``qy/resources/libqy/include/qy.h`` 一致：
  ``{ i8 tag, [7 x i8], [3 x i64] payload }``（32 bytes / align 8）。
- LLVM 与 C 之间的结构体 ABI 必须精确匹配：32-byte 结构体在 SysV 上以
  ``sret`` 返回、以 ``byval`` 传参。本模块的所有 ``qy_*`` 声明、以及编译出的
  ``qy_fn_N``，都用 ``ptr sret(%qy_value) align 8`` / ``ptr byval(%qy_value)
  align 8``，与 clang 为 ``qy.h`` 生成的签名一致。使用 opaque pointer（``ptr``）。
- 寄存器是 entry block 中的 ``alloca %qy_value``；每个 def / use 都走内存，
  因此任意 CFG 都不需要 SSA phi / dominance 处理。
- ``LOAD_ENV`` 在编译期解析：参数 / ``STORE_LOCAL`` / ``DEFINE_ONCE`` 绑定
  快照进 ``%env_N`` alloca；函数自身名支持直接自递归；数字字面量内联构造
  ``%qy_value``；内建算子走 ``qy_builtin_fn``；其余符号走 ``qy_resolve_sym``。
- 模块契约：``@qy_fn_table`` / ``@qy_fn_table_size`` / ``@qy_main`` 与 C
  ``@main``，可被 libqy 的 ``qy_main_c`` 使用；``@main`` 打印顶层结果。

当前支持：int/nil/T/string、内建算术/比较、无自由变量的 defun/lambda、let、
cond/pipeline 控制流、CALL/TAIL_CALL（无 TCO）。effect / module / macro /
并行 opcode 降成 nil 占位，保持 IR 有效。
"""

from __future__ import annotations

from qy.backend.llvm.abi import BUILTIN_NAMES
from qy.backend.llvm.abi import BUILTIN_OPS
from qy.backend.llvm.abi import fn_symbol
from qy.backend.llvm.abi import str_global
from qy.backend.llvm.abi import sym_global
from qy.ir.lir import LIRFunction
from qy.ir.lir import LIRProgram

__all__ = ["compile_to_llvm_text", "emit"]

_VALUE = "ptr sret(%qy_value) align 8"
_BYVAL = "ptr byval(%qy_value) align 8"

_HEADER = """; generated by qy llvm backend
; target: x86_64-unknown-linux-gnu / ABI: System V (opaque pointers)

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%qy_value = type { i8, [7 x i8], [3 x i64] }
%qy_env = type opaque

declare void @qy_init()
declare void @qy_builtin_fn(ptr sret(%qy_value) align 8, i64)
declare void @qy_call(ptr sret(%qy_value) align 8, ptr byval(%qy_value) align 8, ptr, i64)
declare void @qy_make_function(ptr sret(%qy_value) align 8, i64, ptr, i64)
declare void @qy_make_string(ptr sret(%qy_value) align 8, ptr, i64)
declare void @qy_resolve_sym(ptr sret(%qy_value) align 8, ptr)
declare void @qy_car(ptr sret(%qy_value) align 8, ptr byval(%qy_value) align 8)
declare void @qy_cdr(ptr sret(%qy_value) align 8, ptr byval(%qy_value) align 8)
declare void @qy_cons(ptr sret(%qy_value) align 8, ptr byval(%qy_value) align 8, ptr byval(%qy_value) align 8)
declare void @qy_println(ptr byval(%qy_value) align 8)
declare void @qy_abort(ptr)
"""


def _escape(text: str) -> str:
    """Escape a Python string for an LLVM c"..." constant."""
    out = []
    for byte in text.encode("utf-8"):
        if 0x20 <= byte < 0x7F and byte not in (0x22, 0x5C):
            out.append(chr(byte))
        else:
            out.append(f"\\{byte:02X}")
    return "".join(out)


class _FunctionEmitter:
    def __init__(self, function: LIRFunction, fn_idx: int, constants: dict[str, str]) -> None:
        self.function = function
        self.fn_idx = fn_idx
        self.constants = constants
        self.pc = 0
        self.temp = 0
        self.lines: list[str] = []
        self.env_cursor = 0
        self.env_slots = len(function.params) + sum(
            1 for inst in function.instructions if inst.opcode in ("STORE_LOCAL", "DEFINE_ONCE")
        )
        self.scopes: list[dict[str, int]] = [{}]
        for param in function.params:
            self.scopes[0][param.name] = self.env_cursor
            self.env_cursor += 1

    # -- helpers -------------------------------------------------------------

    def out(self, text: str) -> None:
        self.lines.append(text)

    def fresh(self) -> str:
        self.temp += 1
        return f"%t{self.temp}"

    def load(self, slot: str) -> str:
        value = self.fresh()
        self.out(f"  {value} = load %qy_value, ptr {slot}")
        return value

    def _store_int(self, slot: str, number: int) -> None:
        staged = self.fresh()
        self.out(f"  {staged} = insertvalue %qy_value zeroinitializer, i8 2, 0")
        value = self.fresh()
        self.out(f"  {value} = insertvalue %qy_value {staged}, i64 {number}, 2, 0")
        self.out(f"  store %qy_value {value}, ptr {slot}")

    def _store_tag(self, slot: str, tag: int) -> None:
        value = self.fresh()
        self.out(f"  {value} = insertvalue %qy_value zeroinitializer, i8 {tag}, 0")
        self.out(f"  store %qy_value {value}, ptr {slot}")

    def _store_nil(self, slot: str) -> None:
        self.out(f"  store %qy_value zeroinitializer, ptr {slot}")

    def _bind(self, name: str, source_reg: object) -> None:
        slot = self.env_cursor
        self.env_cursor += 1
        self.scopes[-1][name] = slot
        value = self.load(f"%reg_{source_reg}")
        self.out(f"  store %qy_value {value}, ptr %env_{slot}")

    def _store_symbol(self, slot: str, name: str) -> None:
        """Resolve a symbol at compile time into *slot*, or at runtime otherwise."""
        for scope in reversed(self.scopes):
            if name in scope:
                value = self.load(f"%env_{scope[name]}")
                self.out(f"  store %qy_value {value}, ptr {slot}")
                return
        if name == self.function.name.name and name not in ("<main>", "<lambda>"):
            self.out(
                f"  call void @qy_make_function({_VALUE} {slot},"
                f" i64 0, ptr null, i64 {self.fn_idx})"
            )
            return
        if name in ("true", "T"):
            self._store_tag(slot, 1)
            return
        if name in ("false", "nil", "none"):
            self._store_nil(slot)
            return
        if name in BUILTIN_OPS:
            index = BUILTIN_NAMES.index(name)
            self.out(f"  call void @qy_builtin_fn({_VALUE} {slot}, i64 {index})")
            return
        try:
            integer = int(name)
        except ValueError:
            pass
        else:
            self._store_int(slot, integer)
            return
        global_name = sym_global(self.fn_idx, self.pc, name)
        size = len(name.encode("utf-8")) + 1
        self.constants[global_name] = (
            f'{global_name} = private unnamed_addr constant [{size} x i8] c"{_escape(name)}\\00"'
        )
        self.out(f"  call void @qy_resolve_sym({_VALUE} {slot}, ptr {global_name})")

    def _emit_call(
        self, callee_reg: object, args: tuple, dest: object | None, *, tail: bool
    ) -> None:
        for position, arg in enumerate(args):
            value = self.load(f"%reg_{arg}")
            pointer = self.fresh()
            self.out(
                f"  {pointer} = getelementptr inbounds %qy_value, ptr %call.argv, i64 {position}"
            )
            self.out(f"  store %qy_value {value}, ptr {pointer}")
        target = "%sret" if tail else f"%reg_{dest}"
        self.out(
            f"  call void @qy_call({_VALUE} {target},"
            f" {_BYVAL} %reg_{callee_reg}, ptr %call.argv, i64 {len(args)})"
        )
        if tail:
            self.out("  ret void")

    # -- instruction translation --------------------------------------------

    def emit_instruction(self, inst) -> None:
        opcode = inst.opcode
        ops = inst.operands

        if opcode == "JUMP":
            self.out(f"  br label %block_{ops[-1]}")
            return
        if opcode in ("JUMP_IF_FALSE", "BRANCH_NIL"):
            value = self.load(f"%reg_{ops[0]}")
            tag = self.fresh()
            self.out(f"  {tag} = extractvalue %qy_value {value}, 0")
            isnil = self.fresh()
            self.out(f"  {isnil} = icmp eq i8 {tag}, 0")
            self.out(f"  br i1 {isnil}, label %block_{ops[-1]}, label %block_{self.pc + 1}")
            return
        if opcode == "RETURN":
            value = self.load(f"%reg_{ops[0]}")
            self.out(f"  store %qy_value {value}, ptr %sret")
            self.out("  ret void")
            return
        if opcode == "TAIL_CALL":
            args = tuple(ops[1]) if len(ops) > 1 else ()
            self._emit_call(ops[0], args, None, tail=True)
            return

        match opcode:
            case "ENTER_SCOPE":
                self.scopes.append({})
            case "EXIT_SCOPE":
                if len(self.scopes) > 1:
                    self.scopes.pop()
            case "STORE_LOCAL" | "DEFINE_ONCE":
                self._bind(getattr(ops[0], "name", str(ops[0])), ops[1])
            case "MOVE":
                value = self.load(f"%reg_{ops[1]}")
                self.out(f"  store %qy_value {value}, ptr %reg_{ops[0]}")
            case "LOAD_NIL":
                self._store_nil(f"%reg_{ops[0]}")
            case "LOAD_T":
                self._store_tag(f"%reg_{ops[0]}", 1)
            case "LOAD_HOST":
                self._emit_load_host(ops[0], ops[1] if len(ops) > 1 else None)
            case "LOAD_ENV":
                self._store_symbol(f"%reg_{ops[0]}", getattr(ops[1], "name", str(ops[1])))
            case "MAKE_FUNCTION":
                arity = ops[2] if len(ops) > 2 else 0
                self.out(
                    f"  call void @qy_make_function({_VALUE} %reg_{ops[0]},"
                    f" i64 {arity}, ptr null, i64 {ops[1]})"
                )
            case "CALL":
                self._emit_call(ops[1], tuple(ops[2]) if len(ops) > 2 else (), ops[0], tail=False)
            case "APPEND_RESULT":
                pass
            case _:
                # effect / module / macro / parallel opcodes lower to nil so the
                # module stays valid IR for the current runtime subset.
                if ops:
                    self._store_nil(f"%reg_{ops[0]}")

    def _emit_load_host(self, dest: object, value: object) -> None:
        slot = f"%reg_{dest}"
        if value is None:
            self._store_nil(slot)
        elif isinstance(value, bool):
            self._store_tag(slot, 1) if value else self._store_nil(slot)
        elif isinstance(value, int):
            self._store_int(slot, value)
        elif isinstance(value, str):
            name = self._string_constant(value)
            size = len(value.encode("utf-8")) + 1
            self.out(
                f"  call void @qy_make_string({_VALUE} {slot},"
                f" ptr getelementptr inbounds ([{size} x i8], ptr {name}, i32 0, i32 0),"
                f" i64 {len(value.encode('utf-8'))})"
            )
        else:
            self._store_nil(slot)

    def _string_constant(self, value: str) -> str:
        name = str_global(self.fn_idx, self.pc)
        size = len(value.encode("utf-8")) + 1
        self.constants[name] = f'{name} = private constant [{size} x i8] c"{_escape(value)}\\00"'
        return name

    # -- function ------------------------------------------------------------

    def emit(self) -> str:
        register_count = self.function.register_count
        self.out(
            f"define void @{fn_symbol(self.fn_idx)}("
            "ptr sret(%qy_value) align 8 %sret, i64 %argc, ptr %argv, ptr %env) {"
        )
        self.out("entry:")
        for index in range(register_count):
            self.out(f"  %reg_{index} = alloca %qy_value")
        for index in range(self.env_slots):
            self.out(f"  %env_{index} = alloca %qy_value")
        self.out("  %call.argv = alloca %qy_value, i64 64")
        for index in range(len(self.function.params)):
            pointer = self.fresh()
            self.out(f"  {pointer} = getelementptr inbounds %qy_value, ptr %argv, i64 {index}")
            value = self.load(pointer)
            self.out(f"  store %qy_value {value}, ptr %env_{index}")
        if not self.function.instructions:
            self._store_nil("%sret")
            self.out("  ret void")
            self.out("}")
            return "\n".join(self.lines)
        self.out("  br label %block_0")

        for pc, inst in enumerate(self.function.instructions):
            self.pc = pc
            self.out(f"block_{pc}:")
            self.emit_instruction(inst)
            if inst.opcode not in (
                "JUMP",
                "JUMP_IF_FALSE",
                "BRANCH_NIL",
                "RETURN",
                "TAIL_CALL",
            ):
                if pc + 1 < len(self.function.instructions):
                    self.out(f"  br label %block_{pc + 1}")
                else:
                    self._store_nil("%sret")
                    self.out("  ret void")
        self.out("}")
        return "\n".join(self.lines)


def emit(lir_program: LIRProgram) -> str:
    """Lower a compat LIR program to LLVM IR text."""
    if lir_program.dialect != "compat":
        raise ValueError(f"LLVM backend expects compat LIR, got dialect={lir_program.dialect!r}")
    constants: dict[str, str] = {}
    functions = [
        _FunctionEmitter(function, fn_idx, constants).emit()
        for fn_idx, function in enumerate(lir_program.functions)
    ]
    table_entries = ", ".join(
        f"ptr @{fn_symbol(index)}" for index in range(len(lir_program.functions))
    )
    count = len(lir_program.functions)
    main_idx = lir_program.main
    module = [
        _HEADER,
        f"@qy_fn_table = global [{count} x ptr] [{table_entries}]",
        f"@qy_fn_table_size = constant i64 {count}",
        *constants.values(),
        "",
        f"define void @qy_main({_VALUE} %sret, i64 %argc, ptr %argv, ptr %env) {{",
        f"  call void @{fn_symbol(main_idx)}({_VALUE} %sret, i64 %argc, ptr %argv, ptr %env)",
        "  ret void",
        "}",
        "",
        "define i32 @main(i32 %argc, ptr %argv) {",
        "  call void @qy_init()",
        "  %slot = alloca %qy_value",
        f"  call void @{fn_symbol(main_idx)}({_VALUE} %slot, i64 0, ptr null, ptr null)",
        f"  call void @qy_println({_BYVAL} %slot)",
        "  ret i32 0",
        "}",
        "",
        *functions,
        "",
    ]
    return "\n".join(module)


def compile_to_llvm_text(lir_program: LIRProgram) -> str:
    """Convenience: compile a LIRProgram to LLVM IR text."""
    return emit(lir_program)
