# coding: utf-8
"""Link LLVM IR to a native executable.

Pipeline:
    .ll text -> llc -> .o -> gcc link -> a.out

The linker:
    1. Writes LLVM IR to a temp file
    2. Invokes llc to compile to object file
    3. Invokes gcc to link with libqy
    4. Returns the output executable path

Optional C wrapper (for single-function programs):
    For minimal programs with one function, a simple C wrapper is generated
    that provides main(), qy_main(), and qy_fn_table[].

Environment variables:
    QY_LLC       — path to llc (default: "llc")
    QY_CC        — path to C compiler (default: "gcc")
    QY_LLVM_DIR  — directory containing LLVM tools (default: search PATH)
"""

from __future__ import annotations

import os
import subprocess
import tempfile
from pathlib import Path

__all__ = ["CompileResult", "link"]


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------


class CompileResult:
    """Result of compiling a Qy program to an executable."""

    def __init__(
        self,
        executable: Path,
        ll_text: str,
        ll_path: Path,
        obj_path: Path,
        wrapper_c: str | None = None,
    ):
        self.executable = executable
        self.ll_text = ll_text
        self.ll_path = ll_path
        self.obj_path = obj_path
        self.wrapper_c = wrapper_c

    def run(self, *args: str) -> subprocess.CompletedProcess:
        """Run the executable with the given arguments."""
        return subprocess.run(
            [str(self.executable), *list(args)],
            capture_output=True,
            text=True,
        )


# ---------------------------------------------------------------------------
# Default tool paths
# ---------------------------------------------------------------------------


def _llc() -> str:
    return os.environ.get("QY_LLC", "llc")


def _cc() -> str:
    return os.environ.get("QY_CC", "gcc")


# ---------------------------------------------------------------------------
# C wrapper generator
# ---------------------------------------------------------------------------

_C_WRAPPER_TEMPLATE = """/* qy_c_wrapper.c — auto-generated C wrapper for Qy LLVM backend.
 *
 * Provides main() entry point which calls qy_main_c().
 * qy_main() is provided by the LLVM-compiled Qy functions.
 * qy_fn_table[] is populated by the linker.
 *
 * Generated by qy/backend/llvm/link.py — do not edit manually.
 */

#include "qy.h"

/* qy_fn_N: the LLVM-compiled Qy function at index N.
 * The linker resolves these from the LLVM object file. */
extern qy_value qy_fn_0(int64_t argc, qy_value* argv, qy_env* env);

/* qy_fn_table: array of Qy function pointers */
qy_value (*qy_fn_table[])(int64_t, qy_value*, qy_env*) = {
    qy_fn_0,
};

/* qy_fn_table_size: must match the length of qy_fn_table */
const int64_t qy_fn_table_size = 1;

/* qy_main: the Qy program entry point — calls qy_fn_0 */
qy_value qy_main(int64_t argc, qy_value* argv, qy_env* env) {{
    return qy_fn_0(argc, argv, env);
}}

/* main: C entry point — calls qy_main_c provided by libqy */
int main(int argc, char** argv) {{
    return (int)qy_main_c(argc, argv);
}}
"""


# ---------------------------------------------------------------------------
# Main linking function
# ---------------------------------------------------------------------------


def link(
    ll_text: str,
    output_dir: Path | str | None = None,
    output_name: str = "a.out",
    libqy_dir: Path | str | None = None,
    wrapper: bool = True,
    extra_cflags: list[str] | None = None,
) -> CompileResult:
    """Compile LLVM IR text to a native executable.

    Args:
        ll_text: LLVM IR source text
        output_dir: directory for output files (default: system temp dir)
        output_name: name of the output executable
        libqy_dir: directory containing libqy.a and qy.h (default: qy/resources/libqy)
        wrapper: generate a simple C wrapper if True
        extra_cflags: additional flags to pass to gcc

    Returns:
        CompileResult with paths to all artifacts
    """
    if output_dir is None:
        output_dir = Path(tempfile.gettempdir()) / "qy_llvm"
    else:
        output_dir = Path(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    ll_path = output_dir / f"{output_name}.ll"
    obj_path = output_dir / f"{output_name}.o"
    exe_path = output_dir / output_name

    # Default libqy dir
    if libqy_dir is None:
        libqy_dir = Path(__file__).parent.parent.parent / "resources" / "libqy"
    libqy_dir = Path(libqy_dir)

    # Write LLVM IR
    ll_path.write_text(ll_text)

    # Step 1: llc -filetype=obj hello.ll -o hello.o
    llc_result = subprocess.run(
        [_llc(), "-filetype=obj", str(ll_path), "-o", str(obj_path)],
        capture_output=True,
        text=True,
    )
    if llc_result.returncode != 0:
        raise CompilationError(f"llc failed:\n{llc_result.stderr}")

    wrapper_c: str | None = None
    wrapper_o: Path | None = None

    if wrapper:
        # Generate C wrapper
        wrapper_c = _C_WRAPPER_TEMPLATE
        wrapper_path = output_dir / "qy_c_wrapper.c"
        wrapper_path.write_text(wrapper_c)
        wrapper_c = wrapper_c  # for CompileResult

        # Compile wrapper: gcc -c qy_c_wrapper.c -o qy_c_wrapper.o -I{libqy_dir}/include
        wrapper_o = output_dir / "qy_c_wrapper.o"
        gcc_compile = subprocess.run(
            [
                _cc(),
                "-c",
                "-Wall",
                "-Wextra",
                "-pedantic",
                "-std=c11",
                "-I",
                str(libqy_dir / "include"),
                str(wrapper_path),
                "-o",
                str(wrapper_o),
            ],
            capture_output=True,
            text=True,
        )
        if gcc_compile.returncode != 0:
            raise CompilationError(f"gcc (wrapper compile) failed:\n{gcc_compile.stderr}")

    # Find libqy.a
    libqy_a = libqy_dir / "libqy.a"
    if not libqy_a.exists():
        raise CompilationError(
            f"libqy.a not found at {libqy_a}. Run: python -m qy backend build-libqy"
        )

    # Build link command
    link_cmd = [
        _cc(),
        "-no-pie",
        str(obj_path),
    ]
    if wrapper_o:
        link_cmd.append(str(wrapper_o))
    link_cmd.extend(
        [
            str(libqy_a),
            "-o",
            str(exe_path),
        ]
    )
    if extra_cflags:
        link_cmd.extend(extra_cflags)

    link_result = subprocess.run(link_cmd, capture_output=True, text=True)
    if link_result.returncode != 0:
        raise CompilationError(f"link failed:\n{link_result.stderr}")

    return CompileResult(
        executable=exe_path,
        ll_text=ll_text,
        ll_path=ll_path,
        obj_path=obj_path,
        wrapper_c=wrapper_c,
    )


class CompilationError(Exception):
    """Raised when compilation or linking fails."""

    pass
